### ISSUE TITLE
Missing `/public_key` with Local Store

### ISSUE THREAD

**Issue by aj-foster** [wojtekmach/mini_repo#33] opened 2020-06-17 14:22 UTC
Hello there. Thank you for your work on this project. It is a great platform upon which we can build a custom package management solution.

I'm currently running a modified version of the `master` branch as a release with the default `test_repo`. The following occurs when I request the public key:

```
14:19:59.939 [info]  GET /repos/test_repo/public_key
14:19:59.939 [info]  Sent 404 in 218µs
```

Requests to `/names` and `/versions` succeed as expected. Digging in further, it appears: (1) the public key **is** configured correctly, according to `Application.get_all_env/1`, but (2) the key is not present in the `data` directory.

Do you have any advice? Thank you for your time.

**Comment by wojtekmach** [comment] 2020-06-18 07:15
Hi, this should already work (https://github.com/wojtekmach/mini_repo/commit/6eb7eee008801d9a2a1910256894794de7e0544f), have you merged with master recently?

**Comment by wojtekmach** [comment] 2020-06-18 07:24
Oh, the issue is we write down the public_key to store only when creating the registry for the first time, so if you already had a registry it won't be there.

You'll need to put the file in there manually. Alternatively, as part of the above mentioned commit, I exposed a `rebuild/1` function, so you could run: `MiniRepo.Repository.Server.rebuild(:test_repo)`. I think rebuilding should just work, but I haven't tested it thoroughly and so I didn't document it either.

Let me know if you run into any issues!

**Comment by wojtekmach** [comment] 2020-06-18 07:24
Oh, and if you're building a custom package solution on top of this project, please read this comment: https://github.com/wojtekmach/mini_repo/pull/19#issuecomment-637025844.

**Closed as completed by wojtekmach** 2020-06-18 07:24 UTC

**Comment by aj-foster** [comment] 2020-06-18 18:09
Thank you for the update, and I appreciate you pointing out that comment. Looking forward to what will come in the future. 🙂
